name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build images
        run: |
          docker build -t orchestrator:ci agents/orchestrator
          docker build -t scoring:ci agents/scoring
          docker build -t fairness:ci agents/fairness
          docker build -t selection:ci agents/selection
